### ISSUE TITLE
Rebuild Daily Fortune Function

### ISSUE THREAD

**Issue by Samarium150** [Samarium150/mirai-dice-maid#3]
Reference: [fortune.cpp](https://github.com/Samarium150/cqcpp_dice_maid/blob/master/src/dice_maid/fortune.cpp)

**Comment by LinHeLurking** [comment]
Finished in https://github.com/Samarium150/mirai-dice-maid/commit/84b21425df7a692b52d9337f9a24a3747b3ffeff
